config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
  }
  root to: "homes#index"

  get "/about", to: "homes#about"

  resources :question_sets, except: [:new, :show, :destroy] do
    resources :questions, only: [:create, :destroy]
  end

  get "/new_game", to: "games#new_game", as: "new_game"
  post "/finish/:id", to: "games#finish", as: "finish"
  get "/results", to: "games#results", as: "results"

  mount LetterOpenerWeb::Engine, at: "/inbox", as: "inbox"
end

app/models/question_set.rb
# frozen_string_literal: true
class QuestionSet < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :games, dependent: :destroy

  validates :title, presence: true
  validates_length_of :questions, maximum: 10
end

app/controllers/question_sets_controller.rb
# frozen_string_literal: true
class QuestionSetsController < ApplicationController
  before_action :find_question_set, only: [:edit, :update]

  def index
    @question_sets = QuestionSet.all
    @question_set = QuestionSet.new
  end

  def create
    @question_set = QuestionSet.create(question_set_params)
    redirect_to(question_sets_path)
  end

  def edit
  end

  def update
    @question_set.update(question_set_params)
    redirect_to(edit_question_set_path(@question_set), notice: "Updated!")
  end

  private

  def find_question_set
    @question_set = QuestionSet.find(params[:id])
  end

  def question_set_params
    params.require(:question_set).permit(:title)
  end
end

app/views/question_sets/create.html.erb
<h1>QuestionsSets#create</h1>
<p>Find me in app/views/questions_sets/create.html.erb</p>

app/views/question_sets/edit.html.erb
<div class="log_container">
  <h2>Edit Question Set</h2>
  <%= form_with model: @question_set do |f|%>

    <div class="log_field log_field_column">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="log_field log_actions">
      <%= f.submit "Update title", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

<table>
  <thead>
    <tr>
      <th colspan="4" class="q_align_center">Questions</th>
      <th class="q_align_center">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @question_set.questions.each do |question| %>
      <tr>
        <td colspan="4" class="q_ellipsis"><%= question.title %></td>
        <td><%= link_to 'Destroy', question_set_question_path(@question_set, question), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="log_container">
  <h2>Add New Question</h2>
  <%= form_with model: Question.new, url: question_set_questions_path(@question_set) do |f|%>

    <div class="log_field log_field_column">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>

    <div class="log_field log_field_column">
      <%= f.label :answer %>
      <%= f.text_field :answer %>
    </div>

    <% 3.times do |i| %>
      <div class="log_field log_field_column">
        <%= f.label "proposals".to_sym %>
        <%= f.text_field "proposal_#{i}".to_sym  %>
      </div>
    <% end %>

    <div class="log_field log_actions">
      <%= f.submit "Submit", class: "btn btn-success"  %>
    </div>
  <% end %>
</div>

app/views/question_sets/index.html.erb
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_sets.each do |question_set| %>
      <tr>
        <td><%= question_set.title %></td>
        <td><%= link_to 'Edit', edit_question_set_path(question_set) %></td>
        <td><%= link_to 'Destroy', question_set_path(question_set), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div class="log_container">  
  <%= form_with model: @question_set do |f| %>
    <div class="log_field log_field_column">
      <%= f.label "New Question Set" %>
      <%= f.text_field :title, placeholder: "Title" %>
    </div>

    <div class="log_field log_actions">
      <%= f.submit "Submit",  class: "btn btn-primary" %>
    </div>
  <% end %>
</div>