config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
  }
  root to: "homes#index"

  get "/about", to: "homes#about"

  resources :question_sets, except: [:new, :show, :destroy] do
    resources :questions, only: [:create, :destroy]
  end

  get "/new_game", to: "games#new_game", as: "new_game"
  post "/finish/:id", to: "games#finish", as: "finish"
  get "/results", to: "games#results", as: "results"

  mount LetterOpenerWeb::Engine, at: "/inbox", as: "inbox"
end

app/models/game.rb
# frozen_string_literal: true
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :question_set

  def correct(params)
    question_set.questions.each_with_index do |question, i|
      self.result += 1 if params["question#{i}".to_sym] == question.answer
    end
    save
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_game, only: [:finish]

  def new_game
    @game = Game.create(question_set: QuestionSet.all.sample, user: current_user)
  end

  def finish
    @game.correct(finish_game_params)
    redirect_to(results_path)
  end

  def results
    @games = current_user.games
  end

  private

  def find_game
    @game = Game.find(params[:id])
  end

  def finish_game_params
    params.require(:game).permit(:question0, :question1, :question2, :question3, :question4,
      :question5, :question6, :question7, :question8, :question9)
  end
end

app/views/games/new_game.html.erb
<div class="log_container">
  
  <%= form_with model: @game, url: finish_path(@game), method: :post do |f|%>
    <h2><%= @game.question_set.title %></h2>

    <% @game.question_set.questions.each_with_index do |question, i| %>
      <div class="log_field" style="flex-direction: column;margin: 10px 0;">
        <p><%= question.title %></p>

        <div class="q_picks">
          <% question.picks.each do |pick|%>
            <div class="btn q_pick">
              <%= f.label("answer", pick) %>
              <%= f.radio_button "question#{i}", pick, class: "btn btn-success" %> 
            </div>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="log_field log_actions">
      <%= f.submit "Submit", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/games/results.html.erb
<table>
  <thead>
    <tr>
      <th>Question Set</th>
      <th>Result</th>
    </tr>
  </thead>

  <tbody>
    <% if @games.empty? %>
      <tr>
        <td>No games</td>
        <td>Played</td>
      </tr>
    <% else %>
      <% @games.each do |game| %>
        <tr>
          <td><%= game.question_set.title %></td>
          <td><%= game.result || "Not finished" %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>